/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-03-07 09:51:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsps;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.app.modelBean.*;
import dao.*;
import java.util.*;

public final class EmployeeRegisterForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("dao");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.app.modelBean");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t  <title>Employee Register Form:</title>\r\n");
      out.write("\t  <!-- <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script> -->\r\n");
      out.write("<style>\r\n");
      out.write("#mainDiv {\r\n");
      out.write("    padding-top: 30px;\r\n");
      out.write("    padding-right: 10px;\r\n");
      out.write("    padding-bottom: 50px;\r\n");
      out.write("    padding-left: 255px;\r\n");
      out.write("}\r\n");
      out.write(".mandatory {\r\n");
      out.write("\tcolor: #FF0000;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("function validateForm() {\r\n");
      out.write("    var firstname = document.forms[\"RegForm\"][\"firstname\"].value.trim();\r\n");
      out.write("    var lastname = document.forms[\"RegForm\"][\"lastname\"].value.trim();\r\n");
      out.write("    var dateofjoin = document.forms[\"RegForm\"][\"dateofjoin\"].value;\r\n");
      out.write("    var department = document.forms[\"RegForm\"][\"department\"].value;\r\n");
      out.write("    var mobilenumber = document.forms[\"RegForm\"][\"mobilenumber\"].value.trim();\r\n");
      out.write("    var mobilePattern = /^[0-9]{10}$/;\r\n");
      out.write("    var email = document.forms[\"RegForm\"][\"email\"].value.trim();\r\n");
      out.write("    if (firstname == \"\") {\r\n");
      out.write("        alert(\"First Name must be filled out\");\r\n");
      out.write("        document.forms[\"RegForm\"][\"firstname\"].value=firstname;\r\n");
      out.write("        return false;\r\n");
      out.write("    }else if(firstname.length>20){\r\n");
      out.write("    \talert(\"First Name shouldn't exceed more than 20 Chars\");\r\n");
      out.write("    \tdocument.forms[\"RegForm\"][\"firstname\"].value=firstname;\r\n");
      out.write("        return false;\r\n");
      out.write("    }else if (lastname == \"\") {\r\n");
      out.write("        alert(\"Last Name must be filled out\");\r\n");
      out.write("        document.forms[\"RegForm\"][\"lastname\"].value=lastname;\r\n");
      out.write("        return false;\r\n");
      out.write("    }else if(lastname.length>20){\r\n");
      out.write("    \talert(\"Last Name shouldn't exceed more than 20 Chars\");\r\n");
      out.write("    \tdocument.forms[\"RegForm\"][\"lastname\"].value=lastname;\r\n");
      out.write("        return false;\r\n");
      out.write("    }else if (dateofjoin == \"\") {\r\n");
      out.write("        alert(\"Date Of Join must be filled out\");\r\n");
      out.write("        document.forms[\"RegForm\"][\"dateofjoin\"].value=dateofjoin;\r\n");
      out.write("        return false;\r\n");
      out.write("    }else if(department==\"\"){\r\n");
      out.write("    \talert(\"Please Select a Department\");\r\n");
      out.write("        return false;\r\n");
      out.write("    }else if(mobilenumber==\"\"){\r\n");
      out.write("    \talert(\"Mobile Number must be filled out\");\r\n");
      out.write("        document.forms[\"RegForm\"][\"mobilenumber\"].value=mobilenumber;\r\n");
      out.write("        return false;\r\n");
      out.write("    }else if(mobilenumber.length != 10){\r\n");
      out.write("    \talert(\"Mobile Number should be 10 Numbers\");\r\n");
      out.write("        document.forms[\"RegForm\"][\"mobilenumber\"].value=mobilenumber;\r\n");
      out.write("        return false;\r\n");
      out.write("    }else if(mobilenumber.match(mobilePattern) == null){\r\n");
      out.write("    \talert(\"Mobile Number is not valid\");\r\n");
      out.write("        document.forms[\"RegForm\"][\"mobilenumber\"].value=mobilenumber;\r\n");
      out.write("        return false;\r\n");
      out.write("    }else if(email==\"\"){\r\n");
      out.write("    \talert(\"Email Id must be filled out\");\r\n");
      out.write("        document.forms[\"RegForm\"][\"email\"].value=email;\r\n");
      out.write("        return false;\r\n");
      out.write("    }else if(email.length>50){\r\n");
      out.write("    \talert(\"Email Id shouldn't exceed more than 50 Chars\");\r\n");
      out.write("    \tdocument.forms[\"RegForm\"][\"email\"].value=email;\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-color: #d7e7f3;\">\r\n");

String basePath=request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+request.getContextPath();
System.out.println(basePath);
Object obj = request.getAttribute("emp");
if(obj!=null){ //For Modification
EmployeeReg emp1 = (EmployeeReg)obj;
String empIdStr = "<label><b>Employee Id:</b></label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type='text' name='employeeid' value='"+emp1.getEmpId()+"' readonly ></input><pre></pre>";
request.setAttribute("empIdStr", empIdStr);
}else{ // New Form
	String opts="<option value='M.Tech' >M.Tech</option>"+
			"<option value='B.Tech' >B.Tech</option>"+
			"<option value='Intermediate' >Intermediate</option>"+
			"<option value='SSC' >SSC</option>";
			request.setAttribute("opts", opts);

	DepartmentDao deptDao = new DepartmentDaoImpl(); 
	List<Department> deptList = deptDao.getDepartmentDetails();
	String depts="";
	for (Department dept : deptList) {
		depts = depts+"<option value='"+dept.getDeptId()+"'>"+dept.getDeptName()+"</option>";
	}
	System.out.println(depts);
	request.setAttribute("depts", depts);
			
	String stus="<option value='active'>Active</option>"+
			"<option value='inactive'>Inactive</option>";
			request.setAttribute("stus", stus);
			
			
	String exp="<option value='N'>No</option>"+
			"<option value='Y'>Yes</option>";
			request.setAttribute("exp", exp);
}

 
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("<h2>Employee Register Form:</h2>\r\n");
      out.write("</center>\r\n");
      out.write("<div id=\"mainDiv\">\r\n");
      out.write("\t<a href=\"");
      out.print(basePath);
      out.write("/jsps/EmployeeHomePage.jsp\"><b>Home</b></a><pre></pre>\r\n");
      out.write("\t<form name=\"RegForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RegFormSubmit\" method=\"POST\" onsubmit=\"return validateForm()\">\r\n");
      out.write("\t\t<fieldset style=\"padding-left: 180px;width:  500px;\">\r\n");
      out.write("\t\t<pre></pre>\r\n");
      out.write("         ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empIdStr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("         <label class=\"mandatory\">*</label><label><b>First Name:</b></label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("            <input type=\"text\" name=\"firstname\" required  value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("></input><pre></pre>\r\n");
      out.write("         <label class=\"mandatory\">*</label><label><b>Last Name:</b></label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("  \t\t    <input type=\"text\" name=\"lastname\" required value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.lastName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("></input><pre></pre>\r\n");
      out.write("         <label class=\"mandatory\">*</label><label><b>Date of Join:</b></label>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("         \t<input type=\"date\" name=\"dateofjoin\" required value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.dateOfJoin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ></input><pre></pre>\r\n");
      out.write("         <label class=\"mandatory\">*</label><label><b>Department:</b></label>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("     \t      <select name=\"department\" id=\"department\">\r\n");
      out.write("     \t      <option value=''>Select Department</option>\r\n");
      out.write("  \t     \t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${depts}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("        \t  </select><pre></pre>\r\n");
      out.write("         <label><b>Salary:</b></label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("          \t<input type=\"number\" name=\"salary\"  value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.salary}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("></input><pre></pre>\r\n");
      out.write("         <label><b>Experience:</b></label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("         \t <select name=\"experiance\">\r\n");
      out.write("            \t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("          \t</select><pre></pre> \r\n");
      out.write("      <fieldset  style=\"width: 635px;\">\r\n");
      out.write("        <legend><b>Address:</b></legend>\r\n");
      out.write("          <label><b>Present Address:</b></label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("              <textarea name=\"presentaddress\" rows=\"5\" cols=\"20\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.address.presentAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("             <pre></pre>\r\n");
      out.write("           <label><b>Permanent Address:</b></label>\r\n");
      out.write("              <textarea name=\"permanentaddress\" rows=\"5\" cols=\"20\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.address.permanentAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("      </fieldset>\r\n");
      out.write("      <fieldset id=\"fieldset3\" style=\"padding:20px; width: 200px;\"><pre></pre> \r\n");
      out.write("        <legend><b>Educational Details:</b></legend>\r\n");
      out.write("          <table id=\"EducationalDeatails\" border=\"1\" cellpadding=\"3%\">\r\n");
      out.write("                 <tr>\r\n");
      out.write("                   <th>Qualification</th>\r\n");
      out.write("                   <th>University/College</th>\r\n");
      out.write("                   <th>Percentage</th>\r\n");
      out.write("                   <th>Year Of Completion</th>\r\n");
      out.write("                 </tr>\r\n");
      out.write("                 <tr>\r\n");
      out.write("                   <td><select id=\"qualification\" name=\"qualification\">\r\n");
      out.write("                   \t\t <option value=\"\">Select Qualification</option>\r\n");
      out.write("                   \t\t ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${opts}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                       </select></td>\r\n");
      out.write("                   <td><input type=\"text\" id=\"college\" name=\"college\" value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.qualification.collegeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("></input> </td>\r\n");
      out.write("                   <td><input type=\"number\" id=\"percentage\" name=\"percentage\" min=\"0\" max=\"100\" step=\"0.01\" value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.qualification.percentage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ></input> </td>\r\n");
      out.write("                   <td><input type=\"number\" id=\"year\" name=\"year\" step=\"1\" value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.qualification.yearOfpassedout}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ></input> </td>\r\n");
      out.write("                 </tr>\r\n");
      out.write("          </table><pre></pre>\r\n");
      out.write("                  <pre></pre>\r\n");
      out.write("        </fieldset><pre></pre> \r\n");
      out.write("           <label class=\"mandatory\">*</label><label><b>Mobile Number:</b></label>\r\n");
      out.write("\t\t      <input name=\"mobilenumber\" min=\"0\" required value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.mobileNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("></input><pre></pre> \r\n");
      out.write("           <label class=\"mandatory\">*</label><label><b>Email Id:</b></label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("              <input type=\"email\" id=\"email\" name=\"email\" required value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.emailId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("></input><pre></pre>\r\n");
      out.write("           <label class=\"mandatory\">*</label><label><b>Status:</b></label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("     \t     <select name=\"status\">\r\n");
      out.write("  \t           ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stus}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("             </select><pre></pre>\r\n");
      out.write("               <pre></pre>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n");
      out.write("              <div style=\"padding-left: 188px;\">\r\n");
      out.write("              <input type=\"submit\"  value=\"Save\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  \r\n");
      out.write("              <input type=\"reset\" value=\"clear\">\r\n");
      out.write("              </div>\r\n");
      out.write("    </fieldset>            \r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
